# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://github.com/actions/virtual-environments/blob/master/images/macos
name: CI

on:
  push:
    branches:
      - master
      - ci/**
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.3.app'
    - name: Build iOS
      run: xcodebuild -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12 Pro" -scheme "OrientationKitDemo" build
      working-directory: ./Examples
